import React, { Component } from 'react';
import SwipyDeck from './SwipyDeck'
import './css/App.css';
import homepage_img from './images/homepage.png'
import intro_yes from './images/intro-yes.png'
import intro_no from './images/intro-no.png'
import intro_check from './images/intro-check.svg'
import intro_cross from './images/intro-cross.svg'
import home_icon from './images/home.svg'
import home_icon_dark from './images/home_dark.svg'


const firebase = require("firebase");
require("firebase/firestore");
firebase.initializeApp({
  apiKey: '',
  authDomain: 'ai-gwap.firebaseapp.com',
  projectId: 'ai-gwap'
});
var db = firebase.firestore();
var collection = db.collection('sample-static');


class AIQuiz extends Component {
  constructor(props) {
    super(props);
    this.state = {
      gameState: "home", //home, intro, game, end
      gameData: [],
    };
  }

  componentDidMount(){
      //change the url when the view is mounted
      this.props.setMenu(1)
  }
  changeState(gameState) {
    this.setState({gameState: gameState});
  }

  initializeGame() {
    this.changeState('intro');
    var docRef = collection.doc('images');
    docRef.get().then((doc) => {
      if (doc.exists) {
        const raw_data = doc.data();
        const name = raw_data.classLabels[0];
        var data = [];
        for (let i = 0; i < 3; ++i) {
          var item = {};
          item.name = name;
          item.featureViz = raw_data.correctURLs[i];
          data.push(item);
        }
        this.setState({
          gameData: data,
        }, () => {console.log("Loca data:", this.state.gameData);});
        // console.log("Document data:", doc.data());
      } else {
        // doc.data() will be undefined in this case
        console.log("No such document!");
      }
    }).catch(function(error) {
      console.log("Error getting document:", error);
    });
  }

  endGame() {

  }

  render() {
    if (this.state.gameState === 'home') {
      return (
        <div className="aiQuiz_App">
          <img className="HomepageImg" src={homepage_img} alt="AI Quizzes, who has similar AI taste as you at CMU?"/>
          <div className='AlignToBottom'>
            <div className="Btn HomepageBtn SelfCenter" onClick={(e) => this.initializeGame()}>START QUIZ</div>
            <a className='SelfCenter' href="#">Back to project homepage</a>
          </div>
        </div>
      );
    } else if (this.state.gameState === 'intro') {
      return (
        <div className="aiQuiz_App">
          <div className='IntroTitle'>Before you start...</div>
          <div className='SpaceBelow'>In this quiz, you’ll need to judge if the “feature visualization” generated by Machine Learning (GoogleNet) can reflect a feature of an object, for instance:</div>
          <div className='FlexH SmallSpaceBelow'>
            <img className='IntroExample' src={intro_yes} alt='a correct example for Snail'/>
            <img className='IntroExampleMark' src={intro_check} alt='correct'/>
            <div className='IntroExampleText' >This is a Snail.</div>
          </div>
          <div className='FlexH'>
            <img className='IntroExample' src={intro_no} alt='a wrong example for Snail'/>
            <img className='IntroExampleMark' src={intro_cross} alt='wrong'/>
            <div className='IntroExampleText' >This is NOT a Snail.</div>
          </div>
          <div className='AlignToBottom'>
            <a className='SelfCenter' onClick={(e) => this.changeState('game')}>Let’s Get Started!</a>
          </div>
        </div>
      );
    } else if (this.state.gameState === 'game') {
      return (
        <div className="aiQuiz_App">
          <img className='BackHome' src={home_icon} alt="return to homepage" onClick={(e) => this.changeState('home')}/>
          <SwipyDeck handler={this.changeState.bind(this)} data={this.state.gameData}/>
        </div>
      );
    } else if (this.state.gameState === 'end') {
      return (
        <div className="aiQuiz_App Light">
          <img className='BackHome' src={home_icon_dark} alt="return to homepage" onClick={(e) => this.changeState('home')}/>
          <div className='ResultTitleSmall'>You have the most smilar AI taste with</div>
          <div className='ResultTitle'>Tom Mitchell</div>
          <img className='ResultImg' src={require('./images/sample-result.png')}/>
          <div className='ResultBtns'>
            <div className="Btn ShareBtn">SHARE</div>
            <div className="Btn AgainBtn" onClick={(e) => this.changeState('game')}>AGAIN</div>
          </div>
        </div>
      );
    }
  }
}

export default AIQuiz;
